#!/usr/bin/env node
// Regenerates writeups/posts.js from the frontmatter of every writeups/*.md.
//
//   node build-posts.js
//
// Adding a writeup is now: drop `<slug>.md` in writeups/ with frontmatter
// (title, tag, date, ctf, desc), then run this. The slug is the filename.
// Posts are sorted newest-first by `date`. TAG_COLORS + the tagColor helper
// live in posts.js too and are preserved verbatim — this only rewrites the
// window.POSTS array between the generated markers.

const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, 'writeups');
const OUT = path.join(DIR, 'posts.js');
const FIELDS = ['slug', 'date', 'tag', 'ctf', 'title', 'desc'];

// Frontmatter parser — same semantics as MD.parseFrontMatter in markdown.js
// (colon-split, trim, strip one layer of matching quotes) so the build and the
// live article page always read the files identically.
function parseFrontMatter(text) {
  const meta = {};
  const body = text.trim();
  const m = body.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
  if (!m) return meta;
  m[1].split('\n').forEach(function (line) {
    const idx = line.indexOf(':');
    if (idx === -1) return;
    const key = line.slice(0, idx).trim();
    let val = line.slice(idx + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) val = val.slice(1, -1);
    meta[key] = val;
  });
  return meta;
}

function jsStr(s) {
  return "'" + String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
}

const files = fs.readdirSync(DIR).filter(function (f) { return f.endsWith('.md'); });

const posts = files.map(function (f) {
  const slug = f.replace(/\.md$/, '');
  const meta = parseFrontMatter(fs.readFileSync(path.join(DIR, f), 'utf8'));
  const missing = ['title', 'tag', 'date', 'ctf', 'desc'].filter(function (k) { return !meta[k]; });
  if (missing.length) {
    console.warn('  ! ' + f + ' — missing frontmatter: ' + missing.join(', '));
  }
  return { slug: slug, date: meta.date || '', tag: meta.tag || '',
           ctf: meta.ctf || '', title: meta.title || slug, desc: meta.desc || '' };
});

// Newest first. Dates are ISO (YYYY-MM-DD) so string compare is chronological.
posts.sort(function (a, b) { return a.date < b.date ? 1 : a.date > b.date ? -1 : 0; });

const entries = posts.map(function (p) {
  const body = FIELDS.map(function (k) { return '    ' + k + ': ' + jsStr(p[k]); }).join(',\n');
  return '  {\n' + body + '\n  }';
}).join(',\n');

const generated =
  '// AUTO-GENERATED by build-posts.js from writeups/*.md frontmatter.\n' +
  '// Do not edit the POSTS array by hand — edit the .md files and re-run\n' +
  '//   node build-posts.js\n' +
  'window.POSTS = [\n' + entries + '\n];';

// Preserve everything after the POSTS array (TAG_COLORS + tagColor helper),
// which is hand-maintained config, not per-post data.
const TAIL_MARK = '// Tag color tokens';
let tail = '';
try {
  const prev = fs.readFileSync(OUT, 'utf8');
  const at = prev.indexOf(TAIL_MARK);
  if (at !== -1) tail = prev.slice(at);
} catch (e) { /* first run — no existing file */ }

if (!tail) {
  console.error('Could not find "' + TAIL_MARK + '" in posts.js — refusing to ' +
    'overwrite so TAG_COLORS/tagColor are not lost. Restore that section first.');
  process.exit(1);
}

fs.writeFileSync(OUT, generated + '\n\n' + tail);
console.log('Wrote ' + path.relative(__dirname, OUT) + ' — ' + posts.length + ' posts:');
posts.forEach(function (p) { console.log('  ' + p.date + '  ' + p.slug); });
