// AUTO-GENERATED by build-posts.js from writeups/*.md frontmatter.
// Do not edit the POSTS array by hand — edit the .md files and re-run
//   node build-posts.js
window.POSTS = [
  {
    slug: 'secret-base-mkii',
    date: '2025-09-29',
    tag: 'crypto',
    ctf: 'CUHK CTF 2025',
    title: 'Secret Base MKII',
    desc: 'Cracking the "ultra-Robust Skulking Approach" — an upgraded obfuscation scheme that still gave up its secret base.'
  },
  {
    slug: 'ai-teacher',
    date: '2025-04-27',
    tag: 'AI',
    ctf: 'Poly U CTF 2025',
    title: 'AI Teacher',
    desc: 'Prompt-injecting an LLM-backed grading bot into coughing up the flag.'
  },
  {
    slug: 'simple-aes',
    date: '2025-04-27',
    tag: 'crypto',
    ctf: 'Poly U CTF 2025',
    title: 'Simple AES',
    desc: 'A byte-at-a-time AES oracle — feeding controlled blocks into the encrypt endpoint until the flag falls out.'
  }
];

// Tag color tokens shared by the listing + article pages.
window.TAG_COLORS = {
  pwn:    { lbg: '#fce8e6', lfg: '#c0392b', dbg: '#3a201d', dfg: '#ff9b8a' },
  web:    { lbg: '#e7eefc', lfg: '#2c5bb8', dbg: '#1d2a44', dfg: '#8fb4f6' },
  rev:    { lbg: '#f0e9fb', lfg: '#7c3aed', dbg: '#2a2140', dfg: '#c6a8f6' },
  crypto: { lbg: '#e6f6ee', lfg: '#1f9254', dbg: '#16291f', dfg: '#68d99a' },
  AI:     { lbg: '#fdf0e6', lfg: '#c2651a', dbg: '#2e2115', dfg: '#f0a860' },
  misc:   { lbg: '#e8eef0', lfg: '#3b6fd6', dbg: '#1c2530', dfg: '#8fb4f6' }
};

// Resolve a tag to its colors for the theme currently applied on <html>.
window.tagColor = function (tag) {
  var tc = window.TAG_COLORS[tag] || window.TAG_COLORS.misc;
  var dark = document.documentElement.getAttribute('data-theme') === 'dark';
  return { fg: dark ? tc.dfg : tc.lfg, bg: dark ? tc.dbg : tc.lbg };
};
